// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDmdw425MAKT0dtyiivSGGwsHr9ZpeUw6E',
    appId: '1:144975936496:web:daa09f86387741d2723b35',
    messagingSenderId: '144975936496',
    projectId: 'chatwithme-2303f',
    authDomain: 'chatwithme-2303f.firebaseapp.com',
    storageBucket: 'chatwithme-2303f.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChfPdvJapfX_Zy6lS8Q8ssu5WdGktuYco',
    appId: '1:144975936496:android:89d01498cba669d1723b35',
    messagingSenderId: '144975936496',
    projectId: 'chatwithme-2303f',
    storageBucket: 'chatwithme-2303f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCt85GYcm13vgSEyPzpFUIp3kBpALzflIk',
    appId: '1:144975936496:ios:6b1dac8e9b81d10f723b35',
    messagingSenderId: '144975936496',
    projectId: 'chatwithme-2303f',
    storageBucket: 'chatwithme-2303f.appspot.com',
    iosBundleId: 'com.example.chatWithMe',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCt85GYcm13vgSEyPzpFUIp3kBpALzflIk',
    appId: '1:144975936496:ios:6b1dac8e9b81d10f723b35',
    messagingSenderId: '144975936496',
    projectId: 'chatwithme-2303f',
    storageBucket: 'chatwithme-2303f.appspot.com',
    iosBundleId: 'com.example.chatWithMe',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDmdw425MAKT0dtyiivSGGwsHr9ZpeUw6E',
    appId: '1:144975936496:web:8af8e89564a6bfc2723b35',
    messagingSenderId: '144975936496',
    projectId: 'chatwithme-2303f',
    authDomain: 'chatwithme-2303f.firebaseapp.com',
    storageBucket: 'chatwithme-2303f.appspot.com',
  );
}
